2025-05-25T10:13:55.939779655Z Downloading multidict-6.4.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (223 kB)
2025-05-25T10:13:55.948371792Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 223.7/223.7 kB 35.0 MB/s eta 0:00:00
2025-05-25T10:13:55.960265972Z Downloading propcache-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (232 kB)
2025-05-25T10:13:55.968610123Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 232.5/232.5 kB 38.7 MB/s eta 0:00:00
2025-05-25T10:13:55.981296086Z Downloading pydantic-2.11.5-py3-none-any.whl (444 kB)
2025-05-25T10:13:55.994814675Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 444.2/444.2 kB 42.2 MB/s eta 0:00:00
2025-05-25T10:13:56.007754894Z Downloading pydantic_core-2.33.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
2025-05-25T10:13:56.032396781Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 2.0/2.0 MB 89.3 MB/s eta 0:00:00
2025-05-25T10:13:56.043900785Z Downloading requests-2.32.3-py3-none-any.whl (64 kB)
2025-05-25T10:13:56.050068499Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 64.9/64.9 kB 13.2 MB/s eta 0:00:00
2025-05-25T10:13:56.061397021Z Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
2025-05-25T10:13:56.076163634Z Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
2025-05-25T10:13:56.0924669Z Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
2025-05-25T10:13:56.09887207Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 78.5/78.5 kB 15.5 MB/s eta 0:00:00
2025-05-25T10:13:56.111189939Z Downloading typing_extensions-4.13.2-py3-none-any.whl (45 kB)
2025-05-25T10:13:56.118388442Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 45.8/45.8 kB 7.6 MB/s eta 0:00:00
2025-05-25T10:13:56.129996633Z Downloading werkzeug-3.1.3-py3-none-any.whl (224 kB)
2025-05-25T10:13:56.137787176Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 224.5/224.5 kB 36.0 MB/s eta 0:00:00
2025-05-25T10:13:56.149171862Z Downloading yarl-1.20.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (358 kB)
2025-05-25T10:13:56.15761776Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 358.1/358.1 kB 51.8 MB/s eta 0:00:00
2025-05-25T10:13:56.168487Z Downloading packaging-25.0-py3-none-any.whl (66 kB)
2025-05-25T10:13:56.174786264Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 66.5/66.5 kB 12.5 MB/s eta 0:00:00
2025-05-25T10:13:56.186596408Z Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
2025-05-25T10:13:56.201798Z Downloading certifi-2025.4.26-py3-none-any.whl (159 kB)
2025-05-25T10:13:56.209646678Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 159.6/159.6 kB 26.3 MB/s eta 0:00:00
2025-05-25T10:13:56.221483883Z Downloading charset_normalizer-3.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (147 kB)
2025-05-25T10:13:56.228844338Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 147.3/147.3 kB 24.8 MB/s eta 0:00:00
2025-05-25T10:13:56.240456639Z Downloading typing_inspection-0.4.1-py3-none-any.whl (14 kB)
2025-05-25T10:13:56.257831137Z Downloading urllib3-2.4.0-py3-none-any.whl (128 kB)
2025-05-25T10:13:56.265655633Z    ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ‚îÅ 128.7/128.7 kB 20.2 MB/s eta 0:00:00
2025-05-25T10:13:56.277009916Z Downloading h11-0.16.0-py3-none-any.whl (37 kB)
2025-05-25T10:13:56.334578177Z Building wheels for collected packages: telegram, urlobject
2025-05-25T10:13:56.33567482Z   Building wheel for telegram (pyproject.toml): started
2025-05-25T10:13:56.538689979Z   Building wheel for telegram (pyproject.toml): finished with status 'done'
2025-05-25T10:13:56.539655294Z   Created wheel for telegram: filename=telegram-0.0.1-py3-none-any.whl size=1324 sha256=7ce14be090f290ee6eb420135bfa138b2961c082fb90f42cdb521542dcf92ef4
2025-05-25T10:13:56.539864788Z   Stored in directory: /opt/render/.cache/wheels/1e/b7/10/7a0e3b8f8c01e0d9d8a1e9913251932ca9f0a394e98ade3056
2025-05-25T10:13:56.542654676Z   Building wheel for urlobject (pyproject.toml): started
2025-05-25T10:13:56.761571143Z   Building wheel for urlobject (pyproject.toml): finished with status 'done'
2025-05-25T10:13:56.762592162Z   Created wheel for urlobject: filename=urlobject-2.4.3-py3-none-any.whl size=14534 sha256=bcd96bd6128673e3ddf4fa7610d48042c17d4643b791f5bd1bc6926d07446064
2025-05-25T10:13:56.762790625Z   Stored in directory: /opt/render/.cache/wheels/63/69/1e/27e9ecc1870bf9862cc2fb31933b498d6cc6a350e5569d424a
2025-05-25T10:13:56.764880856Z Successfully built telegram urlobject
2025-05-25T10:13:57.056882247Z Installing collected packages: urlobject, telegram, urllib3, typing-extensions, tqdm, sniffio, pyjwt, psycopg2-binary, propcache, packaging, oauthlib, multidict, markupsafe, jiter, itsdangerous, idna, h11, greenlet, frozenlist, dnspython, distro, click, charset-normalizer, certifi, blinker, attrs, annotated-types, aiohappyeyeballs, yarl, Werkzeug, typing-inspection, sqlalchemy, requests, pydantic-core, jinja2, httpcore, gunicorn, email-validator, anyio, aiosignal, requests-oauthlib, pydantic, httpx, flask, aiohttp, python-telegram-bot, openai, flask-sqlalchemy, flask-login, flask-dance
2025-05-25T10:14:01.708114418Z Successfully installed Werkzeug-3.1.3 aiohappyeyeballs-2.6.1 aiohttp-3.12.0 aiosignal-1.3.2 annotated-types-0.7.0 anyio-4.9.0 attrs-25.3.0 blinker-1.9.0 certifi-2025.4.26 charset-normalizer-3.4.2 click-8.2.1 distro-1.9.0 dnspython-2.7.0 email-validator-2.2.0 flask-3.1.1 flask-dance-7.1.0 flask-login-0.6.3 flask-sqlalchemy-3.1.1 frozenlist-1.6.0 greenlet-3.2.2 gunicorn-23.0.0 h11-0.16.0 httpcore-1.0.9 httpx-0.28.1 idna-3.10 itsdangerous-2.2.0 jinja2-3.1.6 jiter-0.10.0 markupsafe-3.0.2 multidict-6.4.4 oauthlib-3.2.2 openai-1.82.0 packaging-25.0 propcache-0.3.1 psycopg2-binary-2.9.10 pydantic-2.11.5 pydantic-core-2.33.2 pyjwt-2.10.1 python-telegram-bot-22.1 requests-2.32.3 requests-oauthlib-2.0.0 sniffio-1.3.1 sqlalchemy-2.0.41 telegram-0.0.1 tqdm-4.67.1 typing-extensions-4.13.2 typing-inspection-0.4.1 urllib3-2.4.0 urlobject-2.4.3 yarl-1.20.0
2025-05-25T10:14:01.791835356Z 
2025-05-25T10:14:01.791858728Z [notice] A new release of pip is available: 24.0 -> 25.1.1
2025-05-25T10:14:01.791864689Z [notice] To update, run: pip install --upgrade pip
2025-05-25T10:14:07.88966312Z ==> Uploading build...
2025-05-25T10:14:13.505018378Z ==> Uploaded in 4.1s. Compression took 1.5s
2025-05-25T10:14:13.536229166Z ==> Build successful üéâ
2025-05-25T10:14:16.109560788Z ==> Deploying...
2025-05-25T10:16:00.999685665Z ==> No open ports detected, continuing to scan...
2025-05-25T10:16:01.328171304Z ==> Docs on specifying a port: https://render.com/docs/web-services#port-binding
2025-05-25T10:16:11.133873076Z ==> Running 'python main.py'
2025-05-25T10:16:25.728147071Z 2025-05-25 10:16:25,727 - __main__ - INFO - Initializing database...
2025-05-25T10:16:25.778929876Z 2025-05-25 10:16:25,778 - initialize_db - INFO - Creating database tables...
2025-05-25T10:16:27.669604521Z 2025-05-25 10:16:27,669 - initialize_db - INFO - Database tables created successfully!
2025-05-25T10:16:28.94409264Z 2025-05-25 10:16:28,943 - __main__ - INFO - Database initialized successfully.
2025-05-25T10:16:31.990987273Z 2025-05-25 10:16:31,990 - trust_system - INFO - Trust system tables created successfully
2025-05-25T10:16:42.60284227Z 2025-05-25 10:16:42,600 - __main__ - INFO - Starting AI ESCROW BOT...
2025-05-25T10:16:43.098904958Z 2025-05-25 10:16:43,098 - goods_escrow_bot - INFO - üõ°Ô∏è AI ESCROW BOT Started!
2025-05-25T10:16:43.92974145Z 2025-05-25 10:16:43,926 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getMe "HTTP/1.1 200 OK"
2025-05-25T10:16:44.09229359Z 2025-05-25 10:16:44,090 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/deleteWebhook "HTTP/1.1 200 OK"
2025-05-25T10:16:44.098893546Z 2025-05-25 10:16:44,098 - telegram.ext.Application - INFO - Application started
2025-05-25T10:16:44.600978738Z 2025-05-25 10:16:44,599 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:16:44.610667546Z 2025-05-25 10:16:44,601 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:16:44.610684406Z Traceback (most recent call last):
2025-05-25T10:16:44.610691267Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:16:44.610849621Z     if not await do_action():
2025-05-25T10:16:44.610858511Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.610863281Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:16:44.610867251Z     return action_cb_task.result()
2025-05-25T10:16:44.610871862Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611237281Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:16:44.611242941Z     updates = await self.bot.get_updates(
2025-05-25T10:16:44.611246901Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611250982Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:16:44.611255082Z     updates = await super().get_updates(
2025-05-25T10:16:44.611259202Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611264762Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:16:44.611269412Z     await self._post(
2025-05-25T10:16:44.611273872Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:16:44.611278442Z     return await self._do_post(
2025-05-25T10:16:44.611282522Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611286403Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:16:44.611290503Z     return await super()._do_post(
2025-05-25T10:16:44.611294743Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611298903Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:16:44.611312623Z     result = await request.post(
2025-05-25T10:16:44.611315233Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611317794Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:16:44.611320243Z     result = await self._request_wrapper(
2025-05-25T10:16:44.611322694Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:44.611325354Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:16:44.611327754Z     raise Conflict(message)
2025-05-25T10:16:44.611330494Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-05-25T10:16:49.935723285Z 2025-05-25 10:16:49,935 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:16:49.937171023Z 2025-05-25 10:16:49,936 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:16:49.937187214Z Traceback (most recent call last):
2025-05-25T10:16:49.937196124Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:16:49.937201454Z     if not await do_action():
2025-05-25T10:16:49.937205824Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937210074Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:16:49.937213984Z     return action_cb_task.result()
2025-05-25T10:16:49.937218334Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937222565Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:16:49.937226715Z     updates = await self.bot.get_updates(
2025-05-25T10:16:49.937230775Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937234855Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:16:49.937239385Z     updates = await super().get_updates(
2025-05-25T10:16:49.937243535Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937248335Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:16:49.937253365Z     await self._post(
2025-05-25T10:16:49.937257935Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:16:49.937261926Z     return await self._do_post(
2025-05-25T10:16:49.937266056Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937270376Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:16:49.937274806Z     return await super()._do_post(
2025-05-25T10:16:49.937278766Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937282856Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:16:49.937286966Z     result = await request.post(
2025-05-25T10:16:49.937291066Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937295296Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:16:49.937299437Z     result = await self._request_wrapper(
2025-05-25T10:16:49.937303687Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:49.937308037Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:16:49.937322067Z     raise Conflict(message)
2025-05-25T10:16:49.937324917Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-05-25T10:16:56.268363367Z 2025-05-25 10:16:56,268 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:16:56.362360783Z 2025-05-25 10:16:56,268 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:16:56.362381053Z Traceback (most recent call last):
2025-05-25T10:16:56.362385684Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:16:56.362389244Z     if not await do_action():
2025-05-25T10:16:56.362392464Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362396494Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:16:56.362399834Z     return action_cb_task.result()
2025-05-25T10:16:56.362403054Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362406614Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:16:56.362461575Z     updates = await self.bot.get_updates(
2025-05-25T10:16:56.362465846Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362469346Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:16:56.362472296Z     updates = await super().get_updates(
2025-05-25T10:16:56.362475556Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362479396Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:16:56.362483246Z     await self._post(
2025-05-25T10:16:56.362486526Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:16:56.362489656Z     return await self._do_post(
2025-05-25T10:16:56.362492596Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362495747Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:16:56.362498996Z     return await super()._do_post(
2025-05-25T10:16:56.362501807Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362504447Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:16:56.362507147Z     result = await request.post(
2025-05-25T10:16:56.362510187Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362513417Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:16:56.362516517Z     result = await self._request_wrapper(
2025-05-25T10:16:56.362519617Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:16:56.362522757Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:16:56.362525767Z     raise Conflict(message)
2025-05-25T10:16:56.362529507Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-05-25T10:17:02.519008161Z ==> No open ports detected, continuing to scan...
2025-05-25T10:17:02.64878887Z ==> Docs on specifying a port: https://render.com/docs/web-services#port-binding
2025-05-25T10:17:04.099020931Z 2025-05-25 10:17:04,098 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:17:04.099455303Z 2025-05-25 10:17:04,098 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:17:04.099462243Z Traceback (most recent call last):
2025-05-25T10:17:04.099465813Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:17:04.099469273Z     if not await do_action():
2025-05-25T10:17:04.099471723Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099474373Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:17:04.099476823Z     return action_cb_task.result()
2025-05-25T10:17:04.099479413Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099481843Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:17:04.099484183Z     updates = await self.bot.get_updates(
2025-05-25T10:17:04.099486654Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099543435Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:17:04.099548675Z     updates = await super().get_updates(
2025-05-25T10:17:04.099551365Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099554305Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:17:04.099556915Z     await self._post(
2025-05-25T10:17:04.099558645Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:17:04.099560496Z     return await self._do_post(
2025-05-25T10:17:04.099562125Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099563876Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:17:04.099565536Z     return await super()._do_post(
2025-05-25T10:17:04.099567216Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099568916Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:17:04.099570566Z     result = await request.post(
2025-05-25T10:17:04.099572286Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099574046Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:17:04.099575676Z     result = await self._request_wrapper(
2025-05-25T10:17:04.099580866Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:04.099582986Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:17:04.099584666Z     raise Conflict(message)
2025-05-25T10:17:04.099586356Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-05-25T10:17:11.181172529Z 2025-05-25 10:17:11,181 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:17:11.182378151Z 2025-05-25 10:17:11,181 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:17:11.182388801Z Traceback (most recent call last):
2025-05-25T10:17:11.182393612Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:17:11.182398562Z     if not await do_action():
2025-05-25T10:17:11.182402122Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182420452Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:17:11.182422822Z     return action_cb_task.result()
2025-05-25T10:17:11.182425012Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182427312Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:17:11.182429582Z     updates = await self.bot.get_updates(
2025-05-25T10:17:11.182431793Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182434033Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:17:11.182436273Z     updates = await super().get_updates(
2025-05-25T10:17:11.182438453Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182441453Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:17:11.182443763Z     await self._post(
2025-05-25T10:17:11.182446003Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:17:11.182448233Z     return await self._do_post(
2025-05-25T10:17:11.182450483Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182452693Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:17:11.182454993Z     return await super()._do_post(
2025-05-25T10:17:11.182457213Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182459453Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:17:11.182461703Z     result = await request.post(
2025-05-25T10:17:11.182463953Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182466203Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:17:11.182468394Z     result = await self._request_wrapper(
2025-05-25T10:17:11.182470574Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:11.182472854Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:17:11.182475084Z     raise Conflict(message)
2025-05-25T10:17:11.182477324Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-05-25T10:17:22.318004807Z 2025-05-25 10:17:22,317 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:17:22.319044064Z 2025-05-25 10:17:22,318 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:17:22.319059444Z Traceback (most recent call last):
2025-05-25T10:17:22.319063555Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:17:22.319067244Z     if not await do_action():
2025-05-25T10:17:22.319070155Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319072965Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:17:22.319075765Z     return action_cb_task.result()
2025-05-25T10:17:22.319078645Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319081625Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:17:22.319084355Z     updates = await self.bot.get_updates(
2025-05-25T10:17:22.319094455Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319096305Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:17:22.319097975Z     updates = await super().get_updates(
2025-05-25T10:17:22.319099595Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319102585Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:17:22.319106385Z     await self._post(
2025-05-25T10:17:22.319109926Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:17:22.319112946Z     return await self._do_post(
2025-05-25T10:17:22.319115696Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319118686Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:17:22.319121766Z     return await super()._do_post(
2025-05-25T10:17:22.319124526Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319127316Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:17:22.319129766Z     result = await request.post(
2025-05-25T10:17:22.319132326Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319135116Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:17:22.319137886Z     result = await self._request_wrapper(
2025-05-25T10:17:22.319139866Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:22.319141606Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:17:22.319143326Z     raise Conflict(message)
2025-05-25T10:17:22.319145057Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2025-05-25T10:17:38.508026114Z 2025-05-25 10:17:38,507 - httpx - INFO - HTTP Request: POST https://api.telegram.org/bot8196073831:AAFIr04r0XF0Ki2cvhH47LJGK2MMisAPk3A/getUpdates "HTTP/1.1 409 Conflict"
2025-05-25T10:17:38.509108502Z 2025-05-25 10:17:38,508 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
2025-05-25T10:17:38.509120882Z Traceback (most recent call last):
2025-05-25T10:17:38.509126152Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 115, in network_retry_loop
2025-05-25T10:17:38.509130712Z     if not await do_action():
2025-05-25T10:17:38.509134802Z            ^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509139362Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_utils/networkloop.py", line 108, in do_action
2025-05-25T10:17:38.509143553Z     return action_cb_task.result()
2025-05-25T10:17:38.509147643Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509154493Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_updater.py", line 335, in polling_action_cb
2025-05-25T10:17:38.509159193Z     updates = await self.bot.get_updates(
2025-05-25T10:17:38.509163413Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509167643Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 669, in get_updates
2025-05-25T10:17:38.509171853Z     updates = await super().get_updates(
2025-05-25T10:17:38.509176043Z               ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509182534Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 4601, in get_updates
2025-05-25T10:17:38.509208214Z     await self._post(
2025-05-25T10:17:38.509211584Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 697, in _post
2025-05-25T10:17:38.509214444Z     return await self._do_post(
2025-05-25T10:17:38.509217015Z            ^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509219335Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/ext/_extbot.py", line 369, in _do_post
2025-05-25T10:17:38.509221804Z     return await super()._do_post(
2025-05-25T10:17:38.509224365Z            ^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509227055Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/_bot.py", line 726, in _do_post
2025-05-25T10:17:38.509229655Z     result = await request.post(
2025-05-25T10:17:38.509231975Z              ^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509234595Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 197, in post
2025-05-25T10:17:38.509237105Z     result = await self._request_wrapper(
2025-05-25T10:17:38.509239615Z              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-25T10:17:38.509242115Z   File "/opt/render/project/src/.venv/lib/python3.11/site-packages/telegram/request/_baserequest.py", line 355, in _request_wrapper
2025-05-25T10:17:38.509244665Z     raise Conflict(message)
2025-05-25T10:17:38.509247115Z telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running